node:
    hostname: node
    container_name: node
    image: pierophp/node
    ports:
        - "8010:80"
        - "8701:8701"
        - "3000:3000"
        - "3001:3001"
    volumes:
        - ./workdir/www/:/var/www/
